### PR TITLE
Adding ZDC LUT for use with L1TZDC Emulator; to be pushed to cms-data…

### PR DESCRIPTION
**Pull request by cfmcginn**
LUT for L1TZDCProducer, emulator of ZDC l1 trigger for 2023 HI datataking - PR in progress to cmssw here:

https://github.com/cms-sw/cmssw/pull/42634

Simultaneous PR to cms-l1t-offline/L1Trigger-L1TCalorimeter here:

https://github.com/cms-l1t-offline/L1Trigger-L1TCalorimeter/pull/20#

Tagging a few people to track - @ginnocen @bundocka @aloeliger

### CODE REVIEW

**Comment by aloeliger** [comment]
please test

**Comment by aloeliger** [comment]
@cfmcginn According to your email today, it seems like externals really aren't actually the place for this. We need to instead discuss with the o2o/db experts.

**Comment by aloeliger** [comment]
> @cfmcginn According to your email today, it seems like externals really aren't actually the place for this. We need to instead discuss with the o2o/db experts.

After further discussion, perhaps this is the correct location for this for the time being, the relative rate of change of this LUT may be such that having it in the externals for testing while a db solution is created is desirable.

**Comment by aloeliger** [comment]
@smuzaffar The test failures are complaining largely about `past`, which is core python stuff. Is this just a transient python error?

**Comment by cfmcginn** [comment]
> > @cfmcginn According to your email today, it seems like externals really aren't actually the place for this. We need to instead discuss with the o2o/db experts.
> 
> After further discussion, perhaps this is the correct location for this for the time being, the relative rate of change of this LUT may be such that having it in the externals for testing while a db solution is created is desirable.

Understood - please let me know if these test failures require changes by me, will iterate.

**Comment by smuzaffar** [comment]
test parameters:
- pull_request = https://github.com/cms-sw/cmssw/pull/42634

**Comment by smuzaffar** [comment]
please test

> @smuzaffar The test failures are complaining largely about past, which is core python stuff. Is this just a transient python error?

I guess it needs cmssw PR to run properly ?

**Comment by aloeliger** [comment]
+l1

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

**Pull request merged**
