### PR TITLE
updates for stage-2 algs

### PR DESCRIPTION
**Pull request by mulhearn**
These additional changes to L1TCalorimeter data are needed before I can merge the very latest Stage-2 algorithm improvements into CMSSW.

### CODE REVIEW

**Comment by mulhearn** [comment]
@smuzaffar, @degano, @iahmad-khan, @davidlange6 I didn't notice until now that there were additional data changes needed.  Now I can't make my long awaited PR for Stage-2 Calo updates until this is in an IB.  These are all new files so it shouldn't effect anything already in CMSSW.

**Comment by ghost** [comment]
@mulhearn Is this good to go? Shall I merge it?

**Comment by mulhearn** [comment]
@degano yes please go ahead!

**Comment by ghost** [comment]
@mulhearn It's in 80X now: cms-sw/cmsdist#2044. Will be available in the IB tomorrow.

**Pull request merged**
