### PR TITLE
L1T Calo data files Phase1 and Phase2

### PR DESCRIPTION
**Pull request by rekovic**

### CODE REVIEW

**Comment by silviodonato** [comment]
https://github.com/cms-sw/cmssw/pull/30325 is ready. @smuzaffar @mrodozov can we merge this PR?

**Comment by mrodozov** [comment]
+externals

**Comment by smuzaffar** [comment]
+externals
all new files, so yes we can mrge it safely

**Comment by smuzaffar** [comment]
@silviodonato , this has been merged for next 11.2.X IB.

**Pull request merged**
